### ISSUE TITLE
Use ot_round when building glyf

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#152]
https://github.com/googlefonts/fontmake-rs/pull/151#pullrequestreview-1342084790 notes that we should be using ot round. Since it didn't exist until https://github.com/googlefonts/fontations/pull/287 we probably aren't :)

**Comment by anthrotype** [comment]
I assumed that they were becaue the original ot_round was inside write-fonts glyf module, but it's worth confirming that.

**Comment by rsheeter** [comment]
I think there are some values, e.g. bbox, that fontmake-rs is setting directly in some cases. Perhaps that means the only place it's missing is the bbox of composites.

**Comment by rsheeter** [comment]
We have two types, write-fonts Bbox which has i16 min/max and kurbo Rect which uses floats.

We create simple glyphs from bez path via https://github.com/googlefonts/fontations/blob/main/write-fonts/src/tables/glyf.rs#L151. That computes a Rect which is turned into a Bbox using `From<Rect> for Bbox`, which does ot rounding. So far so good I think.

For composite glyphs we lookup the Bbox for the constituant simple glyphs, transform it (which makes a Rect, a box with floats), then turn it into a Bbox using `rect2bbox(rect: Rect) -> Bbox`, which does *not* do ot rounding. We then reduce accumulated Bbox to produce a final Bbox. I think that means we have two obvious problems:

1. We don't ot round in fontmake-rs when computing composite bboxes
1. We convert Rect > Bbox too early, we should keep Rect's until the reduce phase

I'm not sure if it's OK that we use the Bbox from the simple glyph - rounded - as input or if we should compute the Rect for the path and do only one conversion from Rect => Bbox at the end of the reduce. Wdyt?

**Comment by anthrotype** [comment]
No, it's the correct thing to do, and exactly what ufo2ft also does, compute the composite glyphs bounding boxes from the compiled simple TTGlyphs which have ot-rounded bboxes

**Comment by anthrotype** [comment]
fonttools recalcBBoxes option when saving a TTFont also computes the bboxes from the already rounded coordinates that are in glyf, so ufo2ft marches that and computes bboxes from post-rounded coordinates

**Comment by anthrotype** [comment]
> For composite glyphs we lookup the Bbox for the constituant simple glyphs, transform it (which makes a Rect, a box with floats), then turn it into a Bbox

Oh wait... This is not correct, I misunderstood. You can't simply transform the bbox of the simple glyphs, you have to transform their (ot-rounded) coordinates and _then_ compute the bounds of these transformed coordinates.
The bounding box of a transformed shape's control points is not always equal to the bounding box of the transformed bounding box. E.g. think about an ellipsis made up of fuor cubic Béziers; rotate that 45° and compute the control bounds of the transformed points; it won't be the same as the bounds of its original bounding rectangle rotated 45°...

**Comment by anthrotype** [comment]
For reference, here's what fonttools does and we should match

https://github.com/fonttools/fonttools/blob/05872d6878b6caeecff3986fdb36719fd64e41d4/Lib/fontTools/ttLib/tables/_g_l_y_f.py#L1144

**Comment by anthrotype** [comment]
basically you need to first ot_round the simple glyphs' BezPath coordinates (if you are starting from the Glyph IRs; or alternatively you obtain rounded BezPaths from the glyf SimpleGlyphs), then for each composite glyph you want to decompose, traverse the tree of components rooted at that composite glyph accummulating the transforms until you reach the leaves (rounded BezPath of simple glyphs); you then transform the path, compute the bounds and union them, rinse and repeat for each component in the composite.
The bbox of the SimpleGlyphs, which write-fonts has already computed after converting from BezPath, won't be of use in this, for the reason I explained above.

It might be a good idea to spawn a separate work for computing composite glyphs bboxes and start from directly from the Glyph IRs, instead of waiting for the SimpleGlyph themselves to be compiled; what we need to accomplish this task is three things: ot-rounded coordinates of control points of all simple glyphs, a map of {glyph_name: BezPath} to resolve component references; and, for each composite glyph we want to compute the bounds of, a list of components' (glyph_name, transform).

Actually, why don't we write a [ControlBoundsPen](https://github.com/fonttools/fonttools/blob/05872d6878b6caeecff3986fdb36719fd64e41d4/Lib/fontTools/pens/boundsPen.py#L9), add that to https://github.com/googlefonts/fontations/blob/main/write-fonts/src/pens.rs and use it here?

**Comment by anthrotype** [comment]
for implementing the ControlBoundsPen properly, the font-types Pen trait is missing the `addComponent` method from the fontTools AbstractPen, which allows a pen to support components.
The ControlBoundsPen takes a glyphSet parameter which is a Dict[str, Glyph], then when one does glyph.draw(pen) and the glyph is a composite glyph, the draw method calls pen.addComponent method for each component; the addComponent method, in turn, resolves the component references using the glyphSet, wraps itself in a TransformPen (a filter pen that takes another pen and applies transformation before forwrding the drawing commands to the wrapped pen), and then calls base_glyph.draw(transform_pen) -- which repeat that recursively until a simple glyph is found...

**Comment by rsheeter** [comment]
> You can't simply transform the bbox of the simple glyphs

Facepalm. Indeed, that seems entirely obvious in retrospect. Oh well.

> why don't we write a [ControlBoundsPen](https://github.com/fonttools/fonttools/blob/05872d6878b6caeecff3986fdb36719fd64e41d4/Lib/fontTools/pens/boundsPen.py#L9), add that to https://github.com/googlefonts/fontations/blob/main/write-fonts/src/pens.rs and use it here?

Good idea, that makes the transform handling simpler.
