### ISSUE TITLE
Emit hvar

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#210]

**Comment by anthrotype** [comment]
fea-rs has a VariationStoreBuilder with a port of fonttools VarStore optimizer, this could be handy for building other tables that have ItemVariationStore such as HVAR, so maybe we should think about moving it to write-fonts or something that is shared by fontc and fea-rs?

**Comment by anthrotype** [comment]
Another thing about HVAR/VVAR. Right now we store advance width and height in the fontir::ir::GlyphInstance alongside contours and components, following font editor source formats:

https://github.com/googlefonts/fontc/blob/927d330f6846e7ce6ded21b0226b205326d4e55f/fontir/src/ir.rs#L998-L1009

however, this means that whenever a glyph varies in its contours/components it must also provide a width/height, and viceversa. But it is conceivable that some variable glyph only varies in one or the other but not both, and in fact the variations for glyph outlines and metrics are stored in different tables and are not tied together like so.

So I was thinking maybe we could store glyph advances separately from the glyph outlines to allow each glyph to define different locations and thus distinct variation models.

Right now in order to decouple glyph outlines from glyph metrics while still allowing them to be sparse in their own right, in the fonttools varLib merge-multiple-master-TTFs-into-VF workflow we resort to hacks like treating an empty glyph (no contours) as if not present (None) from a non-default master and as such "not participating" for gvar deltas computation, or advances of 0xFFFF to similarly mean the glyph does not participate in computation of {H,V}VAR deltas, treat as if missing from this master TTF.

**Comment by rsheeter** [comment]
> I was thinking maybe we could store glyph advances separately from the glyph outlines to allow each glyph to define different locations and thus distinct variation models

And here I naively thought width 1:1 with outlines. +1 to split them up.

**Comment by rsheeter** [comment]
HVAR is currently the only table fontmake writes that fontc doesn't.

**Comment by anthrotype** [comment]
Fixed by #490 and #527
