### ISSUE TITLE
Consistantly do or do not emit the final line

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#275]
https://github.com/googlefonts/fontmake-rs/blob/62579d5bfa35916c2006b15bab6bc4e0c6f7e0a8/fontir/src/ir.rs#L744-L754

**Comment by anthrotype** [comment]
I double checked this and it was intentional like that, I even added a test to ensure this behavior.

https://github.com/googlefonts/fontmake-rs/blob/62579d5bfa35916c2006b15bab6bc4e0c6f7e0a8/fontir/src/ir.rs#L838-L854

Note that this GlyphPathBuilder works from a list of _points_ (not segments, nor path drawing commands) and is intended to convert from points to kurbo path elements (aka drawing commands).
If the self.path.elements().last() is a PathEl::LineTo, that is because the last point of the closed contour is actually of type "line" (i.e. the last method of GlyphPathBuilder to be called immediately before the GlyphPathBuilder::close_path() was a line_to()).
See how GlyphPathBuilder is used to build a BezPath from norad contour point list in UFO glyph:

https://github.com/googlefonts/fontmake-rs/blob/62579d5bfa35916c2006b15bab6bc4e0c6f7e0a8/ufo2fontir/src/toir.rs#L22-L52

If the current point is already of type "line", and we're closing the BezPath, so this point can be either 1) != first point, in which case we decided we always want to emit an explicit closing line to make closePath noop, or 2) it is an actual duplicate point that overlaps the first point; if we were to _not_ emit a lineTo in the second case, then this duplicate point would be lost because it'd be confused with the closePath-implied closing line. Hence we must emit the lineTo unconditionally when the last point is of type "line".

**Comment by rsheeter** [comment]
> If I apply the following change to make the LineTo case conditional

Naively I think I might have expected to remove the condition from the quad/curve case, that is to literally always output the implicit closing line.

**Comment by anthrotype** [comment]
please let's not rehash the stale discussion we already had in https://github.com/fonttools/fonttools/issues/3093.
In this particular piece of code, we are not dealing with SVG paths in which the spec mandates that `Z` always adds a possibly zero-length line segment.
There is nothing implicit in our source UFO/Glyphs contours which are specified as a list of points, and that's what the GlyphPathBuilder is meant to translate into a kurbo::BezPath (sequence of path drawing commands). Technically this GlyphPathBuilder should really be named ContourPathBuilder because it only works on single contours.

E.g. the following contour is deemed closed because it not start with a "move", thus it should be understood as a cyclical list of points that starts and ends on the same point; there is no implicit line, only 2 cubic curve segments each starting where the previous one ends, a total of (4 - 1) * 2 == 6 points:

```xml
<contour>
  <point x="0" y="0" type="curve" />
  <point x="1" y="1" />
  <point x="2" y="2" />
  <point x="3" y="3" type="curve" />
  <point x="4" y="4" />
  <point x="5" y="5" />
</contour>
```

The relevant passage from the UFO spec is where it describes the "move" point type: https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#point-types
The Glyphs paths work the same way, only difference is they carry an additional `closed` bool flag (instead of signalling the open-ness with the type of the first point "move") and they prefer to store the starting "node" of a closed contour at the end of the nodes list, but the essence does not change. E.g. this is Glyphs v2:

```
1 1 OFFCURVE
2 2 OFFCURVE
3 3 CURVE
4 4 OFFCURVE
5 5 OFFCURVE
0 0 CURVE
```

this is the same as Glyphs v3:

```
(1,1,o)
(2,2,o)
(3,3,c)
(4,4,o)
(5,5,o)
(0,0,c)
```

The way we should encode this closed contour as a BezPath is like this:

```rust
let contour = BezPath::from_vec(vec![
    PathEl::MoveTo((0.0, 0.0)),
    PathEl::CurveTo((1.0, 1.0), (2.0, 2.0), (3.0, 3.0)),
    PathEl::CurveTo((4.0, 4.0), (5.0, 5.0), (0.0, 0.0)),
    ClosePath,
]);
```

... and **not** like this:

```rust
let contour = BezPath::from_vec(vec![
    PathEl::MoveTo((0.0, 0.0)),
    PathEl::CurveTo((1.0, 1.0), (2.0, 2.0), (3.0, 3.0)),
    PathEl::CurveTo((4.0, 4.0), (5.0, 5.0), (0.0, 0.0)),
    PathEl::LineTo((0.0, 0.0)),  // hm wait, where is this coming from?!
    ClosePath,
]);
```

**Comment by rsheeter** [comment]
Fair enough. Is there a terse way to express this we could put in a comment? - it _looks_ like a bug when you glance at that code.

**Comment by rsheeter** [comment]
Maybe I'll try to write one and see if you agree with it
