### ISSUE TITLE
Included feature files not found

### ISSUE THREAD

**Issue by madig** [googlefonts/fontc#296]
1. Try and compile https://github.com/madig/FirerSans/blob/main/sources/FiraSans.designspace
2. :fire: 

```
2023-05-23T21:03:02.584914Z: ThreadId(1): ERROR: Be(Features) failed Be(FeaCompileError(ParseFail(DiagnosticSet { messages: [Diagnostic { message: Message { text: "Failed to load source at 'family.fea': 'No such file or directory (os error 2)'", file: FileId(2), span: Span { start: 8, end: 18 } }, level: Error }], tree: "ParseTree" })))
Error: TasksFailed([(Be(Features), "Fea compilation failure")])
```

The default source just includes a shared family.fea: https://github.com/madig/FirerSans/blob/main/sources/FiraSans-Regular.ufo/features.fea -> https://github.com/madig/FirerSans/blob/main/sources/family.fea

The include path logic is explained in https://github.com/googlefonts/ufo2ft/blob/0d2688cd847d003b41104534d16973f72ef26c40/Lib/ufo2ft/featureCompiler.py#L47-L51.

**Comment by anthrotype** [comment]
thanks for this. Yes, it looks we don't correctly support includes coming from UFOs. The UFO spec says that features.fea inside a UFO package, it is the UFO's parent directory (not the UFO itself as a directory containing the features.fea file) that must be used as the root for the includes therein. That's because the fact that a UFO is represented as a filesystem directory is an implementation detail from the point of view of the UFO spec, and in fact there's UFOZ for zipped UFOs, and potentially a single-file UFO in the future who knows.
I think fea-rs should allow us to customise this with its SourceResolver trait.

This is the bit where we call fea-rs:

https://github.com/googlefonts/fontmake-rs/blob/29afae0689e64684b3192c4a2d3f6f9d1dfe6f4b/fontbe/src/features.rs#L75-L95

fontc currently has two modes depending on --emit-ir option; if true, we write fontir::ir::Features::File enum variant (containing the path to the UFO/features.fea) to a features.yml inside build/; if emit-ir=false we do not write any IR to the build directory but we try to do all in memory, so we have a Features::Memory enum variant containing a String with the features.fea contents (in this case `include(family.fea)` which still points to _somewhere_ [wrong] to the filesystem so it's not technically in-memory?!).

The way ufo2ft/feaLib deal with this is, ufo2ft knows it's building from a UFO and where the latter is, so it passes to feaLib the contents of the UFO's features.fea and an `includeDir` option that points to the parent of the UFO, not the UFO itself (as parent of features.fea), that will be used as the base to resolve includes found in the features.

Maybe we need to change the IR for Features to also store this additional include_dir, and when we go ufo2fontir, we set it to the parent directory of the UFO.

For Glyphs sources, I believe there is no issue because the features are inlined inside the .glyphs source which is a single file, so the includes are relative to that file. In the case of glyphs2fontir, we can store this include_dir as the actual `$(dirname font.glyphs)`. Or we make this field optional and when None we assume the include_dir is the parent of the file where features are written.

**Comment by rsheeter** [comment]
ufo2fontir needs to provide enough information to IR that we can resolve this; shouldn't be a big deal. It's very helpful to have a specific font that fails, ty for that.
