### ISSUE TITLE
Representing path

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#33]
Per f2f w/@anthrotype, perhaps we use a `Vec<Vec<Command>>` where `Vec<Command>` is an svg subpath, as from https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d

**Comment by rsheeter** [comment]
This will be very helpful when we try to fontc nanoemoji config files, and powerful as path is a superset of what fonts typically offer.

**Comment by anthrotype** [comment]
one counter argument to that is that SVG path.d syntax doesn't support TrueType-style quadratic splines with implicit on-curve mid-points. In fact in nanoemoji itself, when we need to convert from FontTools pen commands (where qCurveTo does support TrueType splines) to SVG path we need to decompose the former into individual quadratic bezier segments:

https://github.com/googlefonts/nanoemoji/blob/5e6281b1c881ca3597760a9c0e0ad60ebaed71f4/src/nanoemoji/svg_path.py#L107-L110

**Comment by rsheeter** [comment]
Per further discussion, we'll have an absolute coord only path type with only unique commands, e.g. only long forms.

**Comment by rsheeter** [comment]
Where a command is small, suitable to be `Copy`

**Comment by anthrotype** [comment]
so far what I have look very close to [kurbo::PathEl](https://docs.rs/kurbo/0.8.0/kurbo/enum.PathEl.html), with the only addition of an ImpliedQuadTo (for lack of better name) to describe TrueType-style bezier splines with implied on-curve midpoints:

```rust
/// Instructions that define a glyph contour.
///
/// These are similar to SVG path commands but for a single contour or sub-path.
/// Coordinates are intended to be absolute.
/// A contour may or may not end with a ClosePath.
/// 'ImpliedQuadTo' is intended to define TrueType quadratic bezier splines with implied
/// on-curve points; its Point arg is the off-curve point of a quadratic curve, where
/// the on-curve point is implied to be half-way between it and the following qcurve
/// segment's off-curve point. It can only be followed by QuadTo or another ImpliedQuadTo.
/// A contour normally starts with a MoveTo command to the on-curve point where the
/// contour first segment starts off, unless the contour only contains TrueType-style
/// implied quadratic curves with no on-curve points.
pub enum PathCommand {
    MoveTo(Point),
    LineTo(Point),
    QuadTo(Point, Point),
    ImpliedQuadTo(Point),
    CurveTo(Point, Point, Point),
    ClosePath,
}
```

**Comment by rsheeter** [comment]
@dfrg notes that we need to worry about hinting, may reference points. We do not currently have examples of sources with hints. How does hinting work anyway?!

**Comment by rsheeter** [comment]
Hinting issue moved to #51; I believe here as long as we don't damage the outline it's irrelevent.

**Comment by rsheeter** [comment]
@anthrotype can we close this as fixed by #18?

**Comment by anthrotype** [comment]
well it's not.. unless we're happy to keep the current representation, which is basically the same as UFO GLIF paths as list of points

**Comment by rsheeter** [comment]
I'm not aware of a concrete reason to change the current representation so my thought was we could close this and open a new bug if/when we encounter a specific problem?

**Comment by anthrotype** [comment]
while it's good to be able to _convert_ our IR paths to kurbo::BezPath, I am not 100% convinced that we should _store_ them as such in our IR.
As I wrote in https://github.com/googlefonts/fontmake-rs/pull/111#issuecomment-1401733251, BezPath doesn't let us describe TrueType qcurve splines, we lose the information as to which on-curve is implied or explicit. A TrueType contour can even be completely on-curve-less, with only a big qcurve spline described by a series of off-curve points with on-curve midpoints all implied.
Also I think we currently define GlyphInstance::contours as a `Vec<BezPath>`, but BezPath itself is not restricted to a single contour, it may well contain several move_to each starting a new sub-path (aka "contour"). Do we enforce that the BezPath in our list of contours only contain a single starting move_to? If we wanted to use BezPath properly maybe we should have defined GlyphInstance::path simply as a `BezPath`, rather than a vector of them.
Besides, both our input and output define paths as list of points: i.e. two of our input source formats, UFO and Glyphs, describe their paths as a list of points and can handle TT-style qcurve splines  just fine; of course, the primary output format for our compiler is TrueType Variable Fonts, in which glyf table represent paths as sequence of on/off curve points that comprise either line segments or qcurve splines with implied oncurves.
Converting to BezPath may be useful for shape reuse or other path operations including cu2qu, but I'd argue that representing paths as list of points is more general than as list of segments, as the latter can always be derived from the former whereas the former can't always be roundripped back to its original state after being converted to segments.

**Comment by rsheeter** [comment]
I suspect it's useful to have discrete subpaths / shapes so I like GlyphInstance holding a Vec of them.

@anthrotype explained this morning that points => BezPath => points might produce different points which destroys hinting programs using point indices. That seems like a real concern that potentially does support only using BezPath transiently, such as for shape reuse.

**Comment by rsheeter** [comment]
Key points copied from https://github.com/googlefonts/fontmake-rs/pull/111 for ease of reading:

@cmyr 
> I don't believe that kurbo should support implied offcurve points, which is a very font-specific concept. If we need to maintain this information we should use a custom representation.
> 
> However, thinking out loud: assuming we are _always_ making implied offcurves explicit, and assuming that conversion is deterministic, shouldn't we always end up with interpolation-compatible outlines, assuming we _started_ with them? As in, if there were two outlines that previously had implied off curves, and were interpolatable, then converting them both to have explicit offcurves should mean they are still interpolatable.
> 
> And unless I'm mistaken, the only reason to have implied offcurves at all is that it allows a more efficient representation of the of the glyph data, because you can elide some points. during compilation, I imagine we would want to be analyzing the curve and wherever possible converting segments to use implied off curves?

@anthrotype 

> > is a very font-specific concept
> 
> that's true, but I wasn't impling Kurbo should support, rather than we don't use kurbo BezPaths in our IR but keep paths as list of points instead and convert on-demand, see [#33 (comment)](https://github.com/googlefonts/fontmake-rs/issues/33#issuecomment-1401827683)
> 
> > assuming we are always making implied offcurves explicit, and assuming that conversion is deterministic, shouldn't we always end up with interpolation-compatible outlines, assuming we started with them?
> 
> yes
> 
> > the only reason to have implied offcurves at all is that it allows a more efficient representation of the of the glyph data
> 
> correct
> 
> > because you can elide some points during compilation, I imagine we would want to be analyzing the curve and wherever possible converting segments to use implied off curves?
> 
> you should always think about not just a single path, but multiples interpolatable paths at different locations in a variable design space; eliding the points would have to be made across all glyph masters for them to continue to be interpolatable, which means they can only be implied if they can be made so for all the masters; and being floats that midpoint-ness is always going to be an approximation within some tolerance. Some sources already contains qcurves with implied oncurves; most of them only contain postscript cubic curves that are cu2qu'd in a way that produces such qcurves with implied oncurves; we already have this information (either from the input or after cu2qu), however we lose that when converting to bezpath and then we'd have to reconstruct that once again in order to build glyf and the gvar deltas.

**Comment by rsheeter** [comment]
I think we're finding the current representation works so closing.
