### ISSUE TITLE
[ufo2fontir] Use `stylename` as instance name (not `name`)

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#386]
This sounds good, but I'm not sure what we should do if there's no stylename specified for a given instance? Do we leave it blank, fallback on the actual name, or ??

> I just noticed that we are using the instance `name` attribute to set the fvar's NamedInstance's subfamilyNameID names, but this is wrong, varLib uses the `stylename` attribute of an instance, not its `name` for that purpose. The latter is similar to source.name and only meant to uniquely identify a given DS source/instance element for cross referencing within the doc (should have been called `id` perhaps but it's too late).

https://github.com/fonttools/fonttools/blob/57fb47de3a41c724c3bf1051d00715e08d86141e/Lib/fontTools/varLib/__init__.py#L103-L118

If we use `stylename` here we no longer need to do inst.name.strip_prefix(family_prefix).

_Originally posted by @anthrotype in https://github.com/googlefonts/fontc/pull/376#discussion_r1286960988_

**Comment by anthrotype** [comment]
> what we should do if there's no stylename specified for a given instance? 

fonttools in the linked code above raises an error if it cannot find a suitable style name. It will be there for well-behaved real-world sources. An instance without a stylename makes little sense, to be honest, either as the target for an interpolated, static font (the legacy build pipeline) or for variable font builds.
I am not sure why designspaceLib doesn't mark it as required. Maybe because one could omit it if they do provide the localisedStyleName["en"] variant... (which we don't support either I think).

**Comment by anthrotype** [comment]
Ah... yeah, it is optional because in DesignSpace v5 the instance style name can be synthesized using STAT stylistic attributes defined with axis labels. One private font of ours uses that approach actually so gets a bunch of "unnamed_instance_0" etc. in fvar currently.

**Comment by anthrotype** [comment]
using `stylename` attribute instead of `name` should be trivial to do, but my impression is your font does not have those but relies on DSv5 instance stylenames generated from axis labels (those also used for STAT stylistic attributes). If that's the case, then I think it will take some time to implement in fontc and may be quicker if you patch the fontc-built fvar tables using some post-build script

**Comment by anthrotype** [comment]
> using stylename attribute instead of name should be trivial to do

I'll start working on that

**Comment by anthrotype** [comment]
@RickyDaMa I can confirm that with https://github.com/googlefonts/fontc/pull/481 we build fvar instances named as expected for those two Google private projects
