### ISSUE TITLE
fontc's gvar for Oswald has significantly fewer deltas

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#422]
```shell
$ python resources/scripts/ttx_diff.py ../OswaldFont/sources/Oswald.glyphs
...
  DIFF 'gvar', build/gftools/fontc.gvar.ttx build/gftools/fontmake.gvar.ttx
...
$ diffstat build/gftools/fontmake.gvar.ttx  build/gftools/fontc.gvar.ttx| diffstat
 1 file changed, 206 insertions(+), 5851 deletions(-)
```

Visually there are a few places where the result is significantly different but the vast majority is just fontmake having more deltas, ex

![image](https://github.com/googlefonts/fontc/assets/6466432/6f2be338-bb74-4718-b46a-fb0dab69d6f5)

If some of these are fine/wai I would like ttx_diff to eliminate those cases.

**Comment by behdad** [comment]
I don't think these are fine.

**Comment by rsheeter** [comment]
> I don't think these are fine.

Oops, we concluded the same in IM but evidently I didn't update the issue.

**Comment by anthrotype** [comment]
I believe some of the the diffs are because fonttools varLib does not always use the IUP-optimized deltas (like fontc currently does) but sometimes prefers to store the unoptimized deltas if they happen to serialize to a smaller TupleVariation record. Apparently fewer deltas does not always mean fewer bytes for the complicated way gvar is encoded. The iup_delta_optimize algorithm works on the deltas themselves (replacing some with Nones to make them implied), but does not know about the specifics of gvar serialization.

**Comment by anthrotype** [comment]
I just tried to repro but got loads of `failed to compute deltas: 'Missing a tent for wdth'` seemingly coming from fea-rs, this was using fontc off main HEAD (currently at https://github.com/googlefonts/fontc/commit/23ce03f24d76039bc2f175812b1412c09b03be1f)

**Comment by anthrotype** [comment]
If I checkhout main at a few commits before that (e.g. c267b29), I can then run ttx_diff.py, not exactly sure what broke it.

Anyway, I think my hunch is correct because if I force fontTools to always use the IUP optimized deltas (instead of only when beneficial for size), then the only remaining diff in gvar between fontmake and fontc are the composite glyphs (https://github.com/googlefonts/fontc/issues/398), where fontmake omits the no-op (0,0) deltas whereas fontc does not.


```diff
diff --git a/Lib/fontTools/varLib/__init__.py b/Lib/fontTools/varLib/__init__.py
index b130d5b2a..ca19a6c99 100644
--- a/Lib/fontTools/varLib/__init__.py
+++ b/Lib/fontTools/varLib/__init__.py
@@ -378,7 +378,8 @@ def _add_gvar(font, masterModel, master_ttfs, tolerance=0.5, optimize=True):
                     tupleData, auxData = var_opt.compile(axis_tags)
                     optimized_len = len(tupleData) + len(auxData)

-                    if optimized_len < unoptimized_len:
+                    # if optimized_len < unoptimized_len:
+                    if True:
                         var = var_opt

             gvar.variations[glyph].append(var)
```

**Comment by rsheeter** [comment]
I believe the component issue is tracked in #291 and this issue can be deemed fixed as the remaining glyf and gvar diffs appear to be due to the different componentization
