### ISSUE TITLE
Test a lot of builds

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#724]
@simoncozens has been doing work on automating builds across the collection that we can exploit to build and ttx_diff a lot of fonts. "build me a VF" is an operation (implemented here: https://github.com/googlefonts/gftools/blob/builder2/Lib/gftools/builder/operations/buildVariable.py). Replace that line with a fontc equivalent, and off we go.

This should enable us to test "all the fonts for which we have a known upstream repository and where there's a gftools-bulider configuration file in that repo." At time of writing that means 482 fonts out of 1603.

TODO: add end to end instructions to acquire and build as many google fonts as possible.

**Comment by simoncozens** [comment]
Here is how I would do this:

* https://github.com/simoncozens/gf-dashboard/blob/main/gfautobuilder.py is a driver script which clones each repo with a known upstream and runs gftools-builder on it.
  * It requires a cache file with information about which upstream repos seem like they can be built using gftools-builder.
  * You can download the [cache file directly](https://github.com/simoncozens/gf-dashboard/blob/main/cache.json) or you can generate it yourself with [this script](https://github.com/simoncozens/gf-dashboard/blob/main/list-known-upstreams.py).
    * If you choose to generate the cache file yourself, the `list-known-upstreams.py` script in turn requires the `googlefonts` Python module in the same repo, it requires you to set `GFDIR` on line 13 to your google/fonts checkout directory, and also requires you to set the environment variable `GITHUB_TOKEN` to a valid authentication token.
* Next you will need a version of gftools-builder which uses fontc instead of fontmake.
  * By the time you act on this, builder2 should be merged into the main branch, but in case it's not, start by checking out the builder2 branch of gftools.
  * Edit the files `Lib/gftools/builder/operations/buildVariable.py`, `Lib/gftools/builder/operations/buildTTF.py` and `Lib/gftools/builder/operations/buildOTF.py`, replacing the fontmake command line with the equivalent fontc command line. (The `$fontmake_type` variable means `-g` for Glyphs source, `-m` for designspace and `-u` for ufo; you don't need that font fontc.)
  * Install this modified gftools-builder into your Python environment; you now have a fontc-powered gftools-builder
* Run `gfautobuilder.py` and watch the pretty error messages.

**Comment by rsheeter** [comment]
Based on the comments in #852 I suggest we create a standalone (as in not part of the fontc repo) Rust tool that can do tricks like enumerate sources and stop using https://github.com/googlefonts/gf-dashboard/blob/main/list-known-upstreams.py. That would let us rig a nice "build all known GF sources" for fontc QA.

**Comment by rsheeter** [comment]
https://googlefonts.github.io/fontc_crater/ is live. Sources are enumerated with https://github.com/googlefonts/google-fonts-sources. I think we can call this done, there is work to close the diffs but that's best tracked in individual targetted issues.
