### ISSUE TITLE
handle magic '*origin' anchor in glyphs2ir

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#769]
The anchor propagation code we've gotten from glyphs.app includes a new special case for handling mark anchors. From @anthrotype:

```py
   if layer.anchors and glyph.category == "Mark":
       new_anchors = {a.name: a for a in layer.anchors}
       if "*origin" in new_anchors:
           origin = new_anchors.pop("*origin").position
           for anchor_name, anchor in new_anchors.items():
               new_anchors[anchor_name] = GSAnchor(
                   anchor_name,
                   NSPoint(anchor.position.x - origin.x, anchor.position.y - origin.y),
               )
       return new_anchors
```

this looks like something that should definitely be in the glyphs2ir phase, although it would be nice to know exactly what the rationale/use case is, for this logic.

Additionally it would be really nice to see a clear description of what the glyphs.app anchor naming scheme is; for instance I know that `#` is a magic character, and apparently [`&`  is as well](https://forum.glyphsapp.com/t/multiple-entry-anchors-possible/28825/2) (and I think I recall seeing something that non-alphanumeric prefixes generally have some special behaviour?)

**Comment by cmyr** [comment]
@anthrotype I think this is also something where it would be useful to ping georg; in particular I'd like to get a test case for this, but that would require a better understanding of what we're actually trying to accomplish.

**Comment by anthrotype** [comment]
> it would be nice to know exactly what the rationale/use case is, for this logic

the use case is that.. combining mark glyphs' advance widths are meant to be zero-ed at compile time, however font developers like to keep some non-zero spacing in their mark glyphs otherwise they'd disappear or clash with preceding glyphs when laid out next to other glyphs and they are being edited in Glyphs.app.
In Glyphs.app, zeroing the advance width at compile time does not simply set their width=0, but also shifts the mark glyphs so that their origin is moved all the way to the right (xMax + rightSideBearing): this way they appear to hang somewhere on top of the preceding glyph even if the latter doesn't have mark pos rules. The user can control this shifting behavior using this special `*origin` anchor.

E.g. see https://forum.glyphsapp.com/t/custom-lsb-rsb-for-zero-width-mark-attachment/15943/7

> I'd like to get a test case for this

I'm working on making those right now

**Comment by rsheeter** [comment]
@cmyr is this done? - I feel like I saw code related to handling origin but I'm not immediatley sure if it's complete
