### ISSUE TITLE
Crater needs to run default and gftools mode

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#930]
#929 notes Oswald doesn't match in gftools mode. Crater currently won't notice.

**Comment by cmyr** [comment]
Okay so I've now had quite a bit of time to look into this, and it is naturally much more complicated than I had initially imagined. The main problem is that gftools is not simply an alternative set of flags & build options; it is a fairly complete build system of which the font compiler is merely a part. It is also very specifically designed to generate the binary font artifacts that google fonts will distribute for a given family. It is not a general purpose compiler or toolchain.

Given that our stated goal for `fontc` is to be able to function as a drop-in replacement for `fontmake`, I think it makes sense to define our goals for 'gftools mode' specifically in those terms: we want to be able to run `gftools builder` using both `fontc` and `fontmake`, and we want the whole pipeline to produce the same output for both compilers.

This means that we need to patch gftools to be able to optionally use `fontc`. There are more or less hacky ways to do this, but I think it would be simplest for the time being to just add a `--use-fontc` command-line flag.

It would also be nice if we could control a few other things about `gftools builder`; it would be nice if we could specify an alternative destination for the generated files (afaict gftools always writes the generated artifacts in place, alongside the sources... we can always just move them ourselves after execution I suppose?) and it would also be nice if we could override certain aspects of the `config.yaml` from the command line, so that we could (for instance) optionally skip things like generating instances for variable fonts, CFF outlines, or WOFF2 (at least for the time being).

To make this all work, we will also need to update `ttx_diff.py` so that instead of always driving the build process as well as the diffing, it could be passed a pair of font binaries and just do the diffing bit.

**Comment by rsheeter** [comment]
Ref https://github.com/googlefonts/gftools/pull/1046

**Comment by davelab6** [comment]
Aren't these already all features..?

**Comment by rsheeter** [comment]
We need gftools to build with fontmake and with fontc so we can compare the results for https://googlefonts.github.io/fontc_crater/. It doesn't support that today.

**Comment by anthrotype** [comment]
fontc_crater can now build with gftools using either fontmake or fontc as the underlying font compiler and compare the result thereof

**Comment by rsheeter** [comment]
Much rejoicing!
