### ISSUE TITLE
Implement BE work for static glyph

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#94]
See https://github.com/googlefonts/oxidize/blob/main/text/2022-07-25-PROPOSAL-build-glyphs-in-rust.md.

@cmyr will provide an example of generating a single glyph font using fontations; https://github.com/googlefonts/fontations/issues/206.

Note to self: when building the binary of a glyph we may wish to set all of it's components - which glyph IR gives us - as dependencies to ensure we can do things like compute bounds.

**Comment by anthrotype** [comment]
wtih https://github.com/googlefonts/fontmake-rs/pull/131, we can convert curves to quadratic and compile glyf simple glyphs.
The kurbo cu2qu algorithm returns a vector of QuadSplines, where the implied oncurve points (in the middle of successive quadratic bezier segments) are omitted, just like glyf expects; however, we immediately turn those into atomic QuadBez using QuadSplien.to_quads() where the implied on-curve points are made explicit, thus losing the information as to which oncurve point was previously implied or not. And when we call write-font's SimpleGlyph::from_kurbo, we end up explicitly encoding all these unnecessary oncurve points, thus bloating the glyf table size.

If the lossy, earlt conversion from QuadSpline => QuadBez was intentional/by design (which I am 100% not sure about), then at least by the time we create a glyf SimpleGlyph we need to again prune all the oncurves that can be implied because at equal distance from successive quadratic off-curve points.
Does kurbo provide a way to go from a vector of QuadBez to a (vector of) QuadSpline?
I only see to_quads for going the other way around, here:
https://github.com/linebender/kurbo/blob/master/src/quadspline.rs

**Comment by rsheeter** [comment]
We build static glyphs these days.
